### ISSUE TITLE
about checking whether the sended session is right

### ISSUE THREAD

**Issue by andyhx** [bungle/lua-resty-session#33] opened 2016-11-17 13:51 UTC
hello, i am new bb to web serivce , i  am having problems using  lua-resty-session, i am  trying to verify the session that the browser sended is  origina from the nginx resty part or it is not .I have been searching for some time I cant find a good example  to follow. here are my codes:
```
	local session = require "resty.session".start
	{
	   secret = "623q4hR325t36VsCD3g567922IC0073T",
	   cookie = { persistent = true, lifetime = 280 }
	}
	session.open()
	if session.present then
		-- ngx.print(session.data.name)
		args.sessionids=session.data.name
		args.testsession=1
		args.datasession=session.data
		local ret=rpccall(red, '  LogininfofromSession', 100, args)
	end
	local ret=rpccall(red, 'LoigininfofromPasswordandUsername', 100, args)
	if(ret=='yes')then
		local session = require "resty.session".start
		{
		secret = "623q4hR325t36VsCD3g567922IC0073T",      
		cookie = { persistent = true, lifetime = 280 }
		}
		session.open()	
		session.data.name = "OpenResty Fan"	    
		session:save()
	end
```

 i  try to debug  by step to find when the sentence  session.present wil be l steped into。 And i find  everytime even it is not  original from resty session it will step into  。what i want is simple.When the session sended is original from openresty  calling   LogininfofromSession"  function.When then session sended is not from orignal just skip this part ,and it  call  LoigininfofromPasswordandUsername function;And additionally  how can I get session id from javascript？Can anyone  show me an easy example ,thank you so much !

**Comment by bungle** [comment] 2016-11-17 18:08
First of all don't call `open`if you have already called `start`. It goes like this:

1. new
2. open (this will call new if needed)
3. start (this will call open (and new) if needed)

**Comment by bungle** [comment] 2016-11-17 18:12
Your usage is totally wrong. Why not just:

```lua
local session = require "resty.session".start {
    secret = "623q4hR325t36VsCD3g567922IC0073T",
    cookie = { persistent = true, lifetime = 280 }
}
if session.present then
    args.sessionids=session.data.name
    args.testsession=1
    args.datasession=session.data
    local ret=rpccall(red, '  LogininfofromSession', 100, args)
end
-- what are the args here?
local ret=rpccall(red, 'LoigininfofromPasswordandUsername', 100, args)
if ret== "yes" then
    session.data.name = "OpenResty Fan"	    
    session:save()
end
```

**Comment by bungle** [comment] 2016-11-17 18:19
To get session id you need to disable http-only cookies (which you really shouldn't):

```lua
local session = require "resty.session".start {
    secret = "623q4hR325t36VsCD3g567922IC0073T",
    cookie = {
        persistent = true,
        lifetime = 280,
        httponly = false
    }
}
```

It is all documented here:
https://github.com/bungle/lua-resty-session#boolean-sessioncookiehttponly

**Comment by andyhx** [comment] 2016-11-18 15:55
thank u so much for ur reply, args are arguments get from  nginx headers.I try your code，but it seems  is not right， When printing session.data， session.data.name ，their  value are nil ,they are empty 。But if  I added  session.open() in the else part, somtimes the session.data.name are 
nil  or  "OpenResty Fan"   
if session.present then
----------------------------------------- here how can i verify the session is from my client?
    args.sessionids=session.data.name
    args.testsession=1
    args.datasession=session.data
    local ret=rpccall(red, '  LogininfofromSession', 100, args)
else
    -- what are the args here?
    local ret=rpccall(red, 'LoigininfofromPasswordandUsername', 100, args)
    if ret== "yes" then
----------------------------------------------------------------------
--------- if i add this sentence , it sometimes work
      session.open()

---------------------------
        session.data.name = "OpenResty Fan"     
        session:save()
    end
end
can u help me ?why sometimes the session data are empty ,the session is not expired

**Comment by bungle** [comment] 2016-11-18 16:05
I need your full code. Try to make a minimal example that I can try out.

**Comment by andyhx** [comment] 2016-11-18 16:25
hello @bungle ,,thanks so much,here are my codes
`  local args = ngx.req.get_uri_args()
    ngx.req.read_body()
    local h = ngx.req.get_headers()
    local f = io.open(ngx.req.get_body_file(), 'rb')   
    f:close()
	local username=args.usr
	local passwd=args.passwd
    local session = require "resty.session".start{
	secret = "623q4hR325t36VsCD3g567922IC0073T",
	cookie = { persistent = true, lifetime = 20 } }
	if session.present then	 	
		args.sessionids=session.data.name
	----------- I only want to verify whether the session is from my client
		ngx.say(session.data.name)
		args.testsession=1
		args.datasession=session.data
		local ret=rpccall(red, 'LogininfoSession', 100, args)
	else	
		local ret=rpccall(red, 'LogininfoUsePasswd', 100, args)
		if(ret==1)then
	------------login success i want save the session		
			session.open()	
----------if open function is not here the  session data is always nil values	why?		
			session.data.usr = tostring(username)
			session.data.passwd = tostring(passwd)
			session.data.name = 'OpenResty Fan'			
			ngx.say(session.data.name)			
			session:save()
		end
	end
	--ret='yes'
    ngx.say(json.encode(ret))`

**Comment by andyhx** [comment] 2016-11-19 02:37
@bungle ,Are these codes not  enough,i can explain where you dont understand,thanks!

**Comment by bungle** [comment] 2016-11-19 12:16
yes, I will look at it tomorrow.

**Comment by bungle** [comment] 2016-11-20 12:42
@andyhx,

Ok, I have now looked at this. The problem is basically this:

```
attempt to set ngx.header.HEADER after sending out response headers,
```


This code works correctly (I removed all the extra stuff from there that has nothing to do with this issue):

```lua
location /test {
    content_by_lua_block {
        local session = require "resty.session".start {
            secret = "623q4hR325t36VsCD3g567922IC0073T",
            cookie = {
                persistent = true
            }
        }
        if session.present then
            ngx.log(ngx.ERR, session.data.name)
        else
            session.data.name = 'OpenResty Fan'
            ngx.log(ngx.ERR, session.data.name)
            session:save()
        end
    }
}
```

The problem is THESE lines in your code:

```lua
ngx.say(session.data.name)          
session:save()
```

See, you send body content there. That means you cannot send headers anymore, e.g. a session cookie. If you change this to this:

```lua
session:save()
ngx.say(session.data.name)          
``` 
Your code will work just fine.

I can make extra check in `resty.session` to check if headers have already been sent before trying to set the cookie.

**Comment by bungle** [comment] 2016-11-21 17:55
I just released 2.12 that return nil, error on session:start() etc. whenever you try to send cookie if headers where already sent.

**Comment by bungle** [comment] 2016-11-21 17:56
@andyhx, please close this if this is not an issue anymore.

**Comment by andyhx** [comment] 2016-11-25 07:58
hi,bungle, I am sorry that replying u  late ,it works ,thank u so much

**Closed** 2016-11-25 07:59 UTC
